### ISSUE TITLE
Issue segmenting big cells

### ISSUE THREAD

**Issue by pakiessling** [FZJ-INM1-BDA/celldetection#11]
Congrats on your placement in the challenge!

I am really interested in trying out your model.

I tried out ginoro_CpnResNeXt101UNet-fbe875f1a3e5ce2c on my data and it is really good at picking out the nuclei (Blue stain),
however I want to segment the green stain.
![grafik](https://github.com/FZJ-INM1-BDA/celldetection/assets/104848590/9f80dc66-5c68-4889-807b-138b5317f705)

Do you think there is some preprocessing I can do to accomplish this or is my image too different from the training sets?

**Comment by pakiessling** [comment]
Ok, resizing my image to 512 x 512 massive improves detection:

![grafik](https://github.com/FZJ-INM1-BDA/celldetection/assets/104848590/b8d9fbc3-1583-4560-8b86-933e76ec0bf6)

Any other ideas for RGB setup or normalization?

**Comment by ericup** [comment]
Thanks! Also an interesting use case!
If I understand you correctly, you can try segmenting only the green channel of your RGB image.
You may also want to try different resolutions when applying the model.
Then you can easily [scale the contours](https://github.com/FZJ-INM1-BDA/celldetection/blob/b047ab7c1a91d7dbd24effd716946277fd9c2046/celldetection/ops/cpn.py#L98) to fit the original resolution.

Here's an example for a screenshot of your image:
![green_channel_segmentation](https://github.com/FZJ-INM1-BDA/celldetection/assets/26392957/faceb2ab-e819-4fb7-ac52-ee57ec6a4138)

Not yet perfect, but possibly closer to what you are looking for.

**Comment by pakiessling** [comment]
Oh wow! Thats a gamechanger, thank you so much!

**Comment by pakiessling** [comment]
@ericup could you give me some more details on how you accomplished this? Would you just resize the input to 1000 x 1000 and then scale_contours((1000,1000),(2048,2048),contours)?

**Comment by ericup** [comment]
Exactly! For me the screenshot was about 940x940, so you could do something like this:

```python
original_size = img.shape[:2]
img = cv2.resize(img, (940, 940))
img = cv2.cvtColor(img[..., 1], cv2.COLOR_GRAY2RGB)

... # apply model

contours = cd.ops.cpn.scale_contours(img.shape[:2], original_size, contours)
```
