### ISSUE TITLE
Issue setting up data for training

### ISSUE THREAD

**Issue by LeoMira-1999** [FZJ-INM1-BDA/celldetection#4]
Hi @ericup!

I would like to compliment first of all your repo, nicely done !

It's been a week now that I found out about your repo and been trying to load my cell library images. I've been using your "Cell Detection with Contour Proposal Networks" Notebook as a reference, plus the two other notebook in the demos folder.

The images I have are from dsb2018 and i have two folders of train and test images of 256x256 with no metadata folder and inside both folders are two other folders, images and masks, having respectively the tiff images and masks. How would you proceed?

If you have any idea or approach i'll be glad to hear from you.

Whilst I wait for your response,

Leonardo

**Comment by ericup** [comment]
Hi Leonardo,

Thank you very much!

The data structure sounds a little different from what you would get from the [Broad Institute's website](https://bbbc.broadinstitute.org/BBBC038).
But you have probably something like this right?
```
- train/
-- images/
--- img0.tiff
--- img1.tiff
    ...
-- masks/
--- img0_mask0.tiff
--- img0_mask1.tiff
--- img1_mask0.tiff
--- img1_mask1.tiff
--- img1_mask2.tiff
    ...
```

If you start with the _Cell Detection with Contour Proposal Networks_ demo Notebook, you should replace these lines:
```python
train_bbbc039 = cd.data.BBBC039Train(conf.directory, download=conf.download_data)
val_bbbc039 = cd.data.BBBC039Val(conf.directory)
test_bbbc039 = cd.data.BBBC039Test(conf.directory)
```
with some code that loads your data.

Given the structure you described it could look something like this:

```python
import celldetection as cd
from glob import glob
from imageio import imread
from os.path import basename, dirname, join
import numpy as np

class DataFolder:
    def __init__(self, root):
        self.images, self.masks, self.labels = [], [], []
        self.names = glob(join(root, 'images', '*.tiff'))  # find image names
        for img_name in self.names:
            mask_names = glob(join(dirname(dirname(img_name)), 'masks',  # find masks for image
                                   basename(img_name).replace('.tiff', '*.tiff')))
            self.images.append(imread(img_name))  # read image
            masks = np.stack([imread(mask_name) for mask_name in mask_names], 0)  # read masks
            labels = cd.data.unary_masks2labels(masks).max(-1, keepdims=True)  # convert masks to label image
            self.masks.append(masks), self.labels.append(labels)  # append to list
            
    def __len__(self):
        return len(self.images)
    
    def __getitem__(self, item):
        return self.names[item], self.images[item], self.masks[item], self.labels[item]

train_dsb2018 = DataFolder('./train')
test_dsb2018 = DataFolder('./test')
# name, img, masks, labels = train_dsb2018[0]
```
This example reads all your data from the train or test folder and converts the masks for each image to label images.
Note that this code assumes that each mask contains exactly one object, which should be the case for dsb2018.
If you have just one mask with many objects per image you can have a look at [``cd.data.masks2labels``](https://docs.celldetection.org/en/latest/celldetection.data.html#celldetection.data.cpn.masks2labels) to replace ``cd.data.unary_masks2labels``.
If you are using RGB images you should also change the number of channels in the Config from ``in_channels=1`` to ``in_channels=3``. Apart from that you might want to try different data augmentation and normalization.

I hope this helps and gets you started!

Best regards,
Eric

**Comment by LeoMira-1999** [comment]
Thanks for your amazingly fast response ! 

It did work with your help, my files are .tif, that's the only thing i changed.

I'm having trouble now with the visualization of the data using:
```
def demo_transforms(img, lbl, name=None):
    img = cd.data.normalize_percentile(img, percentile=99.8)
    lbl = lbl.copy()
    
    # Show original
    cd.vis.show_detection(img, contours=cd.data.labels2contours(lbl), contour_linestyle='-')
    if name is not None:
        plt.title(name)
    plt.show()

    # Show transformed
    s = 3
    plt.figure(None, (s * 9, s * 9))
    for i in range(1, s * s + 1):
        plt.subplot(s, s, i)
        trans = transforms(image=img, mask=lbl.astype('int32'))
        t_img, t_lbl = trans['image'], trans['mask']
        cd.data.relabel_(t_lbl)
        plt.title(f'transformed {t_img.dtype.name, t_img.shape, t_lbl.dtype.name, t_lbl.shape}')
        cd.vis.show_detection(t_img, contours=cd.data.labels2contours(t_lbl), contour_linestyle='-')
    plt.show()
```

And i guess this function from your notebook shouldn’t be changed ?: 
```
class Data:
    def __init__(self, data, config, transforms=None, items=None, size=None):
        self.transforms = transforms
        self.gen = cd.data.CPNTargetGenerator(
            samples=config.samples,
            order=config.order,
            max_bg_dist=config.bg_fg_dists[0],
            min_fg_dist=config.bg_fg_dists[1],
        )
        self._items = items or len(data)
        self.data = data
        self.size = size
        self.channels = config.in_channels

    def __len__(self):
        return self._items

    @staticmethod
    def map(image):
        image = image / 127.5
        image -= 1
        if image.ndim == 2:
            image = image[..., None]
        return image.astype('float32')

    @staticmethod
    def unmap(image):
        image = (image + 1) * 127.5
        image = np.clip(image, 0, 255).astype('uint8')
        if image.ndim == 3 and image.shape[2] == 1:
            image = np.squeeze(image, 2)
        return image

    def __getitem__(self, item):
        if item >= len(self):
            raise IndexError('Index out of bounds.')
        item = item % len(self.data)
        
        # Get image and labels
        name, img, _, labels = self.data[item]
        
        # Normalize intensities
        img, labels = np.copy(img).squeeze(), np.copy(labels)
        img = cd.data.normalize_percentile(img, percentile=99.8)
        labels = labels.astype('int32')       
        
        # Optionally crop
        if self.size is not None:
            h, w = self.size
            img, labels = cd.data.random_crop(img, labels, height=h, width=w)
        
        # Optionally transform
        if self.transforms is not None:
            r = self.transforms(image=img, mask=labels)
            img, labels = r['image'], r['mask']

        # Ensure channels exist
        if labels.ndim == 2:
            labels = labels[..., None]
        
        # Relabel to ensure that N objects are marked with integers 1..N
        cd.data.relabel_(labels)
        
        # Feed labels to target generator
        gen = self.gen
        gen.feed(labels=labels)
        
        # Map image to range -1..1
        image = self.map(img)
        
        # Return as dictionary
        return OrderedDict({
            'inputs': image,
            'labels': gen.reduced_labels,
            'fourier': (gen.fourier.astype('float32'),),
            'locations': (gen.locations.astype('float32'),),
            'sampled_contours': (gen.sampled_contours.astype('float32'),),
            'sampling': (gen.sampling.astype('float32'),),
            'targets': labels
        })
```

I went ahead to see appart from the visualization, if the model would train, and now it's in the process of doing so, i'll see if the results are coherent.

Thanks again

Leonardo

**Comment by LeoMira-1999** [comment]
The transformation works fine, i couldn't display the transformed images though but I won't focus on that anymore, 

Indeed, i saved the model the regular torch way. Is there a way i can change the default Fourier Descriptor in the config file or anywhere else to test it in a range(6,18,4)?  

Thanks a lot for all the help you provided!

**Comment by ericup** [comment]
Changing the ``order`` setting in the Config should be sufficient. During test time of a trained model you can also change ``model.order`` to a smaller setting. The model then just omits part of the descriptor and outputs results according to the given order.

If you want to try different configs you might find [this](https://docs.celldetection.org/en/latest/celldetection.html#celldetection.util.schedule.Schedule) helpful.

**Comment by LeoMira-1999** [comment]
Thanks for all the tips again and great work !
